Repository SQLutions-FATEC/API-2-Semestre, pull requests merged in 2024-10, with the labels that each got.

#35 Atualiza seção da documentacao com os links adequados
  README.md
Labels: documentation

#37 Feature/Cria tela inicial de avaliação do aluno
  .gitignore
  .idea/encodings.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/StudentEvaluator.java
  src/main/java/module-info.java
  src/main/resources/student/student-evaluator.fxml
Labels: enhancement

#38 Revert "Feature/Cria tela inicial de avaliação do aluno"
  .gitignore
  .idea/encodings.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/StudentEvaluator.java
  src/main/java/module-info.java
  src/main/resources/student/student-evaluator.fxml
Labels: bug

#40 feat: Adiciona definições das user stories da segunda sprint
  docs/readme.md
Labels: documentation

#44 Atualiza o README com informações corretas
  README.md
Labels: documentation

#46 Feature/ Tela aceitar CSV
  .gitignore
  .idea/dbnavigator.xml
  .idea/workspace.xml
  pom.xml
  src/main/java/app/controllers/ConexaoBanco.java
  src/main/java/app/controllers/ControllerCSV.java
  src/main/java/app/controllers/HomeController.java
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/controllers/StudentEvaluator.java
  src/main/java/module-info.java
  src/main/resources/professor/csvScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/student/mainScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#48 Adiciona alunos na tabela e opções para alterar Sprint
  .idea/workspace.xml
  src/main/java/app/controllers/Aluno.java
  src/main/java/app/controllers/StudentEvaluator.java
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#77 Feat/identifica usuario
  src/main/java/app/controllers/HomeController.java
  src/main/resources/student/mainScreen.fxml
Labels: enhancement

#75 Feat/enviar csv
  .gitignore
  .idea/dbnavigator.xml
  .idea/workspace.xml
  assets/DragõesCibernéticos.csv
  assets/FalcõesDourados.csv
  assets/UnicornsImortais.csv
  assets/csv-example.csv
  pom.xml
  src/main/java/app/controllers/AlunoModel.java
  src/main/java/app/controllers/ControllerCSV.java
  src/main/java/app/controllers/EquipeModel.java
  src/main/java/app/controllers/HomeController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/resources/professor/csvScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#72 Permitir professor que edite o aluno
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/resources/professor/EditStudent.fxml
  src/main/resources/professor/professorScreen.fxml
Labels: enhancement

#74 Tela de definir critérios do semestre
  .env.example
  .gitignore
  .idea/dbnavigator.xml
  .idea/encodings.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  assets/CsvExample.csv
  assets/DragõesCibernéticos.csv
  assets/FalcõesDourados.csv
  assets/UnicornsImortais.csv
  pom.xml
  src/main/java/app/controllers/CSVController.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/HomeController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/controllers/StudentEvaluator.java
  src/main/java/app/helpers/ConexaoBanco.java
  src/main/java/app/models/Aluno.java
  src/main/java/app/models/AlunoModel.java
  src/main/java/app/models/EquipeModel.java
  src/main/java/module-info.java
  src/main/resources/professor/criteriaScreen.fxml
  src/main/resources/professor/csvScreen.fxml
  src/main/resources/professor/editStudentScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#79 Ajusta arquivos para merge com main
  .mvn/wrapper/maven-wrapper.properties
  README.md
  assets/csv/CsvExample.csv
  assets/csv/DragõesCibernéticos.csv
  assets/csv/FalcõesDourados.csv
  assets/csv/UnicornsImortais.csv
  assets/gifs/aluno.gif
  assets/gifs/professor.gif
  assets/images/burndownSprint2.png
  pom.xml
  src/main/resources/student/mainScreen.fxml
Labels: enhancement

#78 Junção da develop-2 com a main
  .env.example
  .github/ISSUE_TEMPLATE/default-template.md
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  assets/csv/CsvExample.csv
  assets/csv/DragõesCibernéticos.csv
  assets/csv/FalcõesDourados.csv
  assets/csv/UnicornsImortais.csv
  assets/gifs/aluno.gif
  assets/gifs/professor.gif
  assets/images/burndownSprint2.png
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/app/controllers/CSVController.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/HomeController.java
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/ConexaoBanco.java
  src/main/java/app/models/Aluno.java
  src/main/java/app/models/AlunoModel.java
  src/main/java/app/models/EquipeModel.java
  src/main/java/module-info.java
  src/main/resources/professor/criteriaScreen.fxml
  src/main/resources/professor/csvScreen.fxml
  src/main/resources/professor/editStudentScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/student/mainScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#80 Atualiza develop-3 com main
  .env.example
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  assets/csv/CsvExample.csv
  assets/csv/DragõesCibernéticos.csv
  assets/csv/FalcõesDourados.csv
  assets/csv/UnicornsImortais.csv
  assets/gifs/aluno.gif
  assets/gifs/professor.gif
  assets/images/burndownSprint2.png
  docs/readme.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/app/controllers/CSVController.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/HomeController.java
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/ConexaoBanco.java
  src/main/java/app/models/Aluno.java
  src/main/java/app/models/AlunoModel.java
  src/main/java/app/models/EquipeModel.java
  src/main/java/module-info.java
  src/main/resources/professor/criteriaScreen.fxml
  src/main/resources/professor/csvScreen.fxml
  src/main/resources/professor/editStudentScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/student/mainScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#81 front tela do professor
  src/main/java/app/controllers/ProfessorController.java
  src/main/resources/professor/SetScore.fxml
  src/main/resources/professor/professorScreen.fxml
Labels: enhancement

#82 Atualiza README com informacoes da sprint 2
  README.md
Labels: documentation
