Repository SQLutions-FATEC/API-2-Semestre, pull requests merged in 2024-11, with the labels that each got.

#85 Feat/professor visualiza media front
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/CSVController.java
  src/main/java/app/controllers/LoginController.java
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/helpers/AverageGradeDAO.java
  src/main/java/app/helpers/DatabaseConnection.java
  src/main/java/app/helpers/Utils.java
  src/main/java/app/models/AverageGradeModel.java
  src/main/java/app/models/EquipeModel.java
  src/main/java/app/models/SprintModel.java
  src/main/java/app/models/UsuarioModel.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/assets/sql/schema.sql
  src/main/resources/professor/averageScreen.fxml
  src/main/resources/professor/csvScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/professor/setScore.fxml
Labels: enhancement

#92 Refactor/Organização e estruturação do código
  src/main/java/app/DAOs/CriteriaDAO.java
  src/main/java/app/DAOs/LoginDAO.java
  src/main/java/app/DAOs/PeriodDAO.java
  src/main/java/app/DAOs/SprintDAO.java
  src/main/java/app/DAOs/TeamDAO.java
  src/main/java/app/DAOs/UserDAO.java
  src/main/java/app/controllers/AddStudentController.java
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/CSVController.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/LoginController.java
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/DatabaseConnection.java
  src/main/java/app/helpers/Utils.java
  src/main/java/app/models/CriteriaModel.java
  src/main/java/app/models/EquipeModel.java
  src/main/java/app/models/PeriodModel.java
  src/main/java/app/models/SprintModel.java
  src/main/resources/professor/addStudentScreen.fxml
  src/main/resources/professor/averageScreen.fxml
  src/main/resources/professor/criteriaScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#93 Feat/Permite adicionar pontuação máxima da equipe por sprint
  src/main/java/app/DAOs/SetScoreDAO.java
  src/main/java/app/DAOs/TeamDAO.java
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/SetScoreController.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/professor/setScore.fxml
Labels: enhancement

#94 Refactor/Otimização de queries
  src/main/java/app/DAOs/AverageGradeDAO.java
  src/main/java/app/DAOs/CriteriaDAO.java
  src/main/java/app/DAOs/SetScoreDAO.java
  src/main/java/app/DAOs/SprintDAO.java
  src/main/java/app/DAOs/TeamDAO.java
  src/main/java/app/DAOs/UserDAO.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/helpers/DatabaseConnection.java
  src/main/java/app/helpers/Utils.java
Labels: enhancement

#88 feat: cria arquivo gerador csv, consulta banco, caminho download csv
  pom.xml
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/CSVGerador.java
  src/main/java/app/controllers/CaminhoDownloads.java
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/QueryDB.java
  src/main/java/app/helpers/DatabaseConnection.java
  src/main/java/app/helpers/Utils.java
  src/main/resources/professor/averageScreen.fxml
Labels: enhancement

#99 Feat/Setup para criar .jar
  assets/images/editDBConnection.png
  assets/images/fileType.png
  assets/images/javaVersion.png
  assets/images/javafxSDK.png
  assets/images/mySqlPage.png
  docs/guide/README.md
  pom.xml
  src/main/java/app/Launcher/Launcher.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/SetSprintDataController.java
  src/main/java/app/helpers/Utils.java
  src/main/java/module-info.java
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/professor/setSprintData.fxml
Labels: documentation, enhancement

#103 Chore/Merge da develop-3 na main
  assets/images/editDBConnection.png
  assets/images/fileType.png
  assets/images/javaVersion.png
  assets/images/javafxSDK.png
  assets/images/mySqlPage.png
  docs/guide/README.md
  pom.xml
  src/main/java/app/DAOs/AverageGradeDAO.java
  src/main/java/app/DAOs/CriteriaDAO.java
  src/main/java/app/DAOs/LoginDAO.java
  src/main/java/app/DAOs/PeriodDAO.java
  src/main/java/app/DAOs/SetScoreDAO.java
  src/main/java/app/DAOs/SprintDAO.java
  src/main/java/app/DAOs/TeamDAO.java
  src/main/java/app/DAOs/UserDAO.java
  src/main/java/app/Launcher/Launcher.java
  src/main/java/app/controllers/AddStudentController.java
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/CSVController.java
  src/main/java/app/controllers/CSVGerador.java
  src/main/java/app/controllers/CaminhoDownloads.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/HomeController.java
  src/main/java/app/controllers/LoginController.java
  src/main/java/app/controllers/Main.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/QueryDB.java
  src/main/java/app/controllers/SetScoreController.java
  src/main/java/app/controllers/SetSprintDataController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/ConexaoBanco.java
  src/main/java/app/helpers/DatabaseConnection.java
  src/main/java/app/helpers/Utils.java
  src/main/java/app/models/Aluno.java
  src/main/java/app/models/AvaliacaoModel.java
  src/main/java/app/models/AverageGradeModel.java
  src/main/java/app/models/CriteriaModel.java
  src/main/java/app/models/EquipeModel.java
  src/main/java/app/models/NotaModel.java
  src/main/java/app/models/PeriodModel.java
  src/main/java/app/models/SprintModel.java
  src/main/java/app/models/TeamModel.java
  src/main/java/app/models/UserModel.java
  src/main/java/module-info.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/assets/sql/schema.sql
  src/main/resources/loginScreen.fxml
  src/main/resources/professor/addStudentScreen.fxml
  src/main/resources/professor/averageScreen.fxml
  src/main/resources/professor/criteriaScreen.fxml
  src/main/resources/professor/editStudentScreen.fxml
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/professor/setScore.fxml
  src/main/resources/professor/setSprintData.fxml
  src/main/resources/student/mainScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#100 Feat/Login aluno e professor
  src/main/java/app/DAOs/UserDAO.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/LoginController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/Utils.java
  src/main/java/app/interfaces/ScreenController.java
  src/main/resources/loginScreen.fxml
  src/main/resources/professor/criteriaScreen.fxml
  src/main/resources/professor/editStudentScreen.fxml
  src/main/resources/professor/setScore.fxml
Labels: enhancement

#118 Fix/Não exibe mais alunos deletados na query
  src/main/java/app/DAOs/AverageGradeDAO.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/QueryDB.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/Utils.java
Labels: bug

#119 Fix/Equipe se associa a um período
  src/main/java/app/DAOs/PeriodDAO.java
  src/main/java/app/DAOs/TeamDAO.java
  src/main/java/app/controllers/AddStudentController.java
  src/main/java/app/controllers/CSVGerador.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/helpers/Utils.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/assets/sql/schema.sql
Labels: bug

#120 Fix/corrigir cálculo média
  src/main/java/app/DAOs/AverageGradeDAO.java
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/models/AverageGradeModel.java
Labels: bug

#121 Feat/Cria período de avaliação do professor e do aluno
  src/main/java/app/DAOs/AverageGradeDAO.java
  src/main/java/app/DAOs/SetScoreDAO.java
  src/main/java/app/DAOs/SprintDAO.java
  src/main/java/app/DAOs/TeamDAO.java
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/LoginController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/SetScoreController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/Utils.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/assets/sql/schema.sql
  src/main/resources/loginScreen.fxml
  src/main/resources/professor/outOfSetScorePeriodScreen.fxml
  src/main/resources/professor/setScore.fxml
  src/main/resources/student/alreadyEvaluatedScreen.fxml
  src/main/resources/student/outOfEvaluationPeriodScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: enhancement

#122 Feat/Ajusta tela de alunos com as informações corretas
  src/main/java/app/DAOs/CriteriaDAO.java
  src/main/java/app/DAOs/GradeDAO.java
  src/main/java/app/DAOs/ScoreDAO.java
  src/main/java/app/DAOs/UserDAO.java
  src/main/java/app/controllers/AddStudentController.java
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/CriteriaController.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/LoginController.java
  src/main/java/app/controllers/OutOfSetScorePeriodController.java
  src/main/java/app/controllers/PastEvaluationsController.java
  src/main/java/app/controllers/SetScoreController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/Utils.java
  src/main/java/app/models/EvaluationModel.java
  src/main/java/app/models/GradeModel.java
  src/main/java/app/models/ScoreModel.java
  src/main/java/app/models/UserModel.java
  src/main/java/module-info.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/professor/outOfSetScorePeriodScreen.fxml
  src/main/resources/student/pastEvaluationsScreen.fxml
  src/main/resources/student/studentScreen.fxml
Labels: bug, enhancement

#125 Fix/Criação de equipes e bugs
  src/main/java/app/DAOs/TeamDAO.java
  src/main/java/app/DAOs/UserDAO.java
  src/main/java/app/controllers/AddStudentController.java
  src/main/java/app/controllers/AverageController.java
  src/main/java/app/controllers/CSVGerador.java
  src/main/java/app/controllers/CaminhoDownloads.java
  src/main/java/app/controllers/EditStudentController.java
  src/main/java/app/controllers/LoginController.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/QueryDB.java
  src/main/java/app/helpers/Utils.java
  src/main/java/app/models/AverageGradeModel.java
  src/main/resources/assets/sql/default_dump.sql
  src/main/resources/assets/sql/dump.sql
  src/main/resources/professor/addStudentScreen.fxml
  src/main/resources/professor/averageScreen.fxml
  src/main/resources/professor/editStudentScreen.fxml
  src/main/resources/professor/professorScreen.fxml
Labels: bug

#128 Refactor/Pequenas correções
  src/main/java/app/DAOs/SprintDAO.java
  src/main/java/app/controllers/ProfessorController.java
  src/main/java/app/controllers/SetSprintDataController.java
  src/main/java/app/controllers/StudentController.java
  src/main/java/app/helpers/Utils.java
  src/main/java/app/models/SprintModel.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/assets/sql/schema.sql
  src/main/resources/professor/professorScreen.fxml
  src/main/resources/professor/setSprintDataScreen.fxml
Labels: bug, enhancement

#104 Feat/aluno visualiza historico avaliacoes
  src/main/java/app/DAOs/CriteriaDAO.java
  src/main/java/app/DAOs/LoginDAO.java
  src/main/java/app/DAOs/PastEvaluationDAO.java
  src/main/java/app/DAOs/SprintDAO.java
  src/main/java/app/controllers/PastEvaluationsController.java
  src/main/java/app/models/PastEvaluationModel.java
  src/main/resources/assets/sql/dump.sql
  src/main/resources/student/alreadyEvaluatedScreen.fxml
  src/main/resources/student/outOfEvaluationPeriodScreen.fxml
  src/main/resources/student/pastEvaluationsScreen.fxml
Labels: help wanted

#130 Fix/Ajusta exibição das médias e da habilitação do botão de relatórios
  src/main/java/app/controllers/AverageController.java
Labels: bug

#127 Feat/remove sprint
  src/main/java/app/DAOs/SprintDAO.java
  src/main/java/app/controllers/SetSprintDataController.java
  src/main/resources/professor/setSprintDataScreen.fxml
Labels: enhancement
